#!/bin/bash

# Add our sources
echo "Creating /etc/apt/sources.list file"
if [ -n "$build_repo" ]; then
    cat << EOF > "$rootfs/etc/apt/sources.list"
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-backports main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-proposed main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-security main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main multiverse restricted universe
# deb-src [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal main contrib non-free
EOF
else
    cat << EOF > "$rootfs/etc/apt/sources.list"
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-backports main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-proposed main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-security main multiverse restricted universe
deb [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main multiverse restricted universe
# deb-src [trusted=yes] http://ports.ubuntu.com/ubuntu-ports/ focal main contrib non-free
EOF
fi

# Create hosts file
echo "I: Creating /etc/hosts file"
cat << EOF > "$rootfs/etc/hosts"
127.0.0.1       kali localhost
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
EOF

# Create default capture folders along with /sdcard, /external_sd, /system, /root/.ssh
echo "I: Creating /root/.ssh directory"
mkdir -p "$rootfs/root/.ssh"

echo "I: Creating /root/.vnc directory"
mkdir -p "$rootfs/root/.vnc"

echo "I: Creating /etc/skel/.vnc directory"
mkdir -p "$rootfs/etc/skel/.vnc"

echo "I: Creating /sdcard, /external_sd, /system mountpoints"
mkdir -p "$rootfs/sdcard" "$rootfs/external_sd" "$rootfs/system"

echo "I: Creating /captures directories"
cap="$rootfs/captures"
mkdir -p "$cap/evilap" "$cap/ettercap" "$cap/kismet/db" "$cap/nmap" \
	"$cap/sslstrip" "$cap/tshark" "$cap/wifite" "$cap/tcpdump" \
	"$cap/urlsnarf" "$cap/dsniff" "$cap/honeyproxy" "$cap/mana/sslsplit"

# Link /lib/modules to /system/lib/modules for modprobe
echo "I: Creating mountpoint /lib/modules"
mkdir -p "$rootfs/lib/modules"

echo "[+] Completed stage 2!"
